### ISSUE TITLE
ModuleNotFoundError: No module named 'auth_decorator'

### ISSUE THREAD

**Issue by noamanhesham** [Vuka951/tutorial-code#6]
requirements.txt has been installed to the env/ , however when I am running the code, I am receiving below error:
```
(env37) $ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/hnoaman/PycharmProjects/react_projects/prototype-search/backend/env37/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/hnoaman/PycharmProjects/react_projects/prototype-search/backend/app.py", line 8, in <module>
    from auth_decorator import login_required
ModuleNotFoundError: No module named 'auth_decorator'
```
Python version:
```
(env37) $ python
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
Installed libs:
```
(env37) $ pip freeze
Authlib==0.14.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cryptography==2.9
entrypoints==0.3
fastapi==0.59.0
flake8==3.7.9
Flask==1.1.2
h11==0.9.0
httptools==0.1.1
idna==2.9
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
mccabe==0.6.1
pycodestyle==2.5.0
pycparser==2.20
pydantic==1.6.1
pyflakes==2.1.1
python-dotenv==0.12.0
requests==2.23.0
six==1.14.0
starlette==0.13.4
urllib3==1.25.8
uvicorn==0.11.5
uvloop==0.14.0
websockets==8.1
Werkzeug==1.0.1
(env37) $ 
```

**Comment by Vuka951** [comment]
What tutorial is this code connected to? (folder name in the repo?)

**Comment by noamanhesham** [comment]
tutorial-code/flask-google-oauth2/app.py /

**Comment by Vuka951** [comment]
Hi, sorry the response is a bit late the issue for you just seems to be that you dont have the auth_decorator.py in the same place as the app.py so it cant find it (the `auth_decorator module`)
